[package]
name = "kryoptic"
version = "0.1.0"
edition = "2021"

[lib]
name = "kryoptic_pkcs11"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.66.1"

[dependencies]
data-encoding = "2.4.0"
getrandom = "0.2.10"
once_cell = "1.18.0"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
uuid = { version = "1.4.1", features = ["v4"] }
